### ISSUE TITLE
Identified font #30

### ISSUE THREAD

**Issue by Compyx** [codepo8/logo-o-matic#2]
Just identified font #30, I thought it looked familiar. It was done by Genius/Strezz Designs, in this demo: http://csdb.dk/release/?id=44676

I recognized the Amica Paint fill-effect which Ryan used, as did Orc.

And #17 is by Flex/Contex, according to him in the CSDB comment which brought me here.

Cheers,
Compyx/Focus

**Comment by codepo8** [comment]
Excellent, adding that now…

**Comment by codepo8** [comment]
Fixed, cheers!
